### ISSUE TITLE
How to SET UTC timezone ?

### ISSUE THREAD

**Issue by D-Niclas** [AppAndFlow/react-native-quickpicker#6]
Hello,

Im wondering is there some way to set time to UTC in the picker now it is AM/PM.

https://www.timeanddate.com/time/aboututc.html

![Skärmavbild 2019-06-26 kl  15 47 28](https://user-images.githubusercontent.com/52247482/60185187-c48a7480-9829-11e9-81fc-4293fa523c31.png)

Best Regrads

Niclas

**Comment by Valiums** [comment]
hey @D-Niclas!

No it's not currently possible however, I believe we could use the "local" props on DatePickerIOS 
https://facebook.github.io/react-native/docs/datepickerios#locale in order to achieve this.

I'll push an updated version later today or tomorrow in order to support this :)

The only thing is, I am not sure this is supported on Android. Nevertheless, this option will be available on iOS.

**Comment by Valiums** [comment]
@D-Niclas done deal !

use version quick-picker@1.4.0
and set locale props to "en-gb" for instance then you'll no longer have the AM/PM

hope that help :)

**Comment by D-Niclas** [comment]
Thnx for fast response, I will try setting locale props =)
